server:
  port: 8080
zuul:
  routes:
    catalog:
#      url: http://localhost:8081
      service-id: catalog-service 
    order:
      service-id: order-service
#      url: http://localhost:8082

catalog-service:
  ribbon:
    eureka:
      enabled: false
  listOfServers: localhost:8081, localhost:8083

order-service:
  ribbon:
    eureka:
      enabled: false
  listOfServers: localhost:8082

management:
  security:
    enabled: false