zuul:
  routes:
    catalog:
      service-id: catalog
    notification:
      service-id: notification
    order:
      service-id: order
catalog:
  ribbon:
    eureka:
      enabled: false
  listOfServers: localhost:8180, localhost:8181
notification:
  ribbon:
    eureka:
      enabled: false
  listOfServers: localhost:8280, localhost:8281
order:
  ribbon:
    eureka:
      enabled: false
  listOfServers: localhost:8380, localhost:8381
  