version: '2'

services:
  mongo:
    image: mongo:3.4.2
    volumes:
      - 'mongo-data:/data/db'
      - 'mongo-config:/data/configdb'
  redis:
    image: redis:4.0.1-alpine
    volumes:
      - 'redis-data:/data'
  config:
    image: example/config:${EXAMPLE_VERSION}
    environment:
      - SPRING_MAIN_BANNER-MODE=off
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  eureka:
    image: example/eureka:${EXAMPLE_VERSION}
    ports: [ '8761:8761' ]
    environment:
      - SPRING_MAIN_BANNER-MODE=off
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
  edge:
    image: example/edge:${EXAMPLE_VERSION}
    ports: [ '8080:8080' ]
    environment:
      - SPRING_MAIN_BANNER-MODE=off
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_URI=http://eureka:8761/eureka
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411/
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  catalog:
    image: example/catalog:${EXAMPLE_VERSION}
    environment:
      - SPRING_MAIN_BANNER-MODE=off
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_URI=http://eureka:8761/eureka
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411/
      - SPRING_DATA_MONGODB_HOST=mongo
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  order:
    image: example/order:${EXAMPLE_VERSION}
    environment:
      - SPRING_MAIN_BANNER-MODE=off
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_URI=http://eureka:8761/eureka
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411/
      - SPRING_DATA_MONGODB_HOST=mongo
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  notification:
    image: example/notification:${EXAMPLE_VERSION}
    environment:
      - SPRING_MAIN_BANNER-MODE=off
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_URI=http://eureka:8761/eureka
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411/
      - SPRING_REDIS_HOST=redis
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.0.0-beta2
    volumes:
      - './metricbeat.yml:/usr/share/metricbeat/metricbeat.yml'
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    volumes:
      - 'es-data:/usr/share/elasticsearch/data'
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.2
    ports: [ '12201:12201/udp' ]
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - XPACK_MONITORING_ENABLED=false
    volumes:
      - './logstash.conf:/usr/share/logstash/pipeline/logstash.conf'
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    ports: [ '5601:5601' ]
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - XPACK_MONITORING_ENABLED=false
  zipkin:
    image: openzipkin/zipkin:2.0.1
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elastic:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=changeme
  zipkin-ui:
    image: openzipkin/zipkin-ui:2.0.1
    ports: [ '9412:80' ]
  

volumes:
  mongo-data:
  mongo-config:
  redis-data:
  es-data:
