metricbeat.modules:
- module: dropwizard
  metricsets: ["collector"]
  period: 10s
  hosts: ["edge:8080", "catalog:8080", "order:8080", "notification:8080"]
  metrics_path: /metrics
  namespace: example
output.elasticsearch:
  hosts: ["elastic:9200"]
  protocol: http
  username: elastic
  password: changeme