server:
  port: 8082
  
management:
  security:
    enabled: false

spring:
  application:
    name: order-service


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
